theme: minima
title: Lamber's Blog
author: Lamber
email: 957742501@qq.com
description: > # this means to ignore newlines until "baseurl:"
  A normal person.Do not stop learning.

# social links
twitter_username: https://twitter.com/Lamber28793923 # DO NOT include the @ character, or else the build will fail!
github_username:  https://github.com/Lamber-maybe # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
